"""Add gift check number and cheque number to settlement."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_gift_check_cheque_numbers'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_check_number', sa.String(50), nullable=True))
        batch_op.add_column(sa.Column('cheque_amount', sa.Float, nullable=True))
        batch_op.add_column(sa.Column('cheque_number', sa.String(50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_column('cheque_number')
        batch_op.drop_column('cheque_amount')
        batch_op.drop_column('gift_check_number')

    # ### end Alembic commands ###
