"""Add cashier_id to Settlement model

Revision ID: f7734b2038ce
Revises: 
Create Date: 2025-10-23 13:16:31.719791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7734b2038ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_order_invoice_no', ['invoice_no'])

    with op.batch_alter_table('order_audit_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_order_audit_logs_reference_no', ['reference_no'])

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_settlement_cashier_id', 'user', ['cashier_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('x_reading', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('previous_grand_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('current_grand_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_reading', schema=None) as batch_op:
        batch_op.alter_column('current_grand_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('previous_grand_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_settlement_cashier_id', type_='foreignkey')
        batch_op.drop_column('cashier_id')

    with op.batch_alter_table('order_audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_order_audit_logs_reference_no', type_='unique')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('uq_order_invoice_no', type_='unique')

    # ### end Alembic commands ###
