"""Remove trxn_no column from Order model

Revision ID: a1b2c3d4e5f7
Revises: f7734b2038ce
Create Date: 2025-12-07 10:39:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f7'
down_revision = 'f7734b2038ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the column exists before trying to drop it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('order')]
    
    if 'trxn_no' in columns:
        with op.batch_alter_table('order', schema=None) as batch_op:
            batch_op.drop_column('trxn_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trxn_no', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_order_trxn_no', ['trxn_no'])
    # ### end Alembic commands ###
